### ISSUE TITLE
Add support for Mongoid 7

### ISSUE THREAD

**Issue by dblock** [mongoid/mongoid-grid_fs#71]
Finish https://github.com/mongoid/mongoid-grid_fs/pull/70

**Comment by leoarnold** [comment]
Solved in https://github.com/mongoid/mongoid-grid_fs/commit/e828e84753575560d669ad7667d40f7dace40503 ?

Probably still open because no gem version supporting Mongoid 7 was published yet

**Comment by dblock** [comment]
Closed via https://github.com/mongoid/mongoid-grid_fs/pull/76
